# Generated by Django 3.0.7 on 2020-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_titel', models.CharField(max_length=250)),
                ('song_artist', models.CharField(max_length=250)),
                ('song_music', models.CharField(max_length=250)),
                ('song_lyrics', models.CharField(max_length=250)),
            ],
        ),
    ]
