# Generated by Django 3.0.7 on 2020-06-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0002_auto_20200607_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
