# Generated by Django 3.0.7 on 2020-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_amazon',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='song_background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='song_itunes',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='song_producer',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AddField(
            model_name='song',
            name='song_publisher',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='song_spotify',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_music',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
