# Generated by Django 3.0.7 on 2020-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0005_auto_20200613_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_year',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
    ]
