# Generated by Django 3.0.7 on 2020-06-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0006_song_song_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_text', models.TextField(blank=True, default='')),
                ('text_chords', models.TextField(blank=True, default='')),
                ('text_nashville', models.TextField(blank=True, default='')),
                ('song', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='songarchiv.Song')),
            ],
        ),
    ]
