# Generated by Django 3.0.7 on 2020-06-17 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0007_song_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_text',
            name='text_chords',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='song_text',
            name='text_nashville',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='song_text',
            name='text_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
