# Generated by Django 3.0.7 on 2020-06-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0008_auto_20200617_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_snippet',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
