# Generated by Django 3.0.7 on 2020-06-21 09:46

from django.db import migrations, models
import songarchiv.models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0009_song_song_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_snippet',
            field=models.FileField(upload_to=songarchiv.models.dynamik_path),
        ),
    ]
