# Generated by Django 3.0.7 on 2020-06-21 10:11

from django.db import migrations, models
import songarchiv.models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0010_auto_20200621_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_snippet',
            field=models.FileField(blank=True, upload_to=songarchiv.models.dynamik_path),
        ),
    ]
