# Generated by Django 3.0.7 on 2020-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0012_auto_20200628_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='album_spotify',
            field=models.CharField(default='', max_length=250),
        ),
    ]
