# Generated by Django 3.0.7 on 2020-07-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0013_auto_20200702_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_amazon_selling',
            field=models.CharField(default='', max_length=250),
        ),
    ]
