# Generated by Django 3.0.7 on 2020-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0014_album_album_amazon_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_amazon_selling',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_spotify',
            field=models.CharField(default='', max_length=500),
        ),
    ]
