# Generated by Django 3.0.7 on 2020-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0016_song_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['album__album_title']},
        ),
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AddField(
            model_name='song',
            name='song_youtube',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
