# Generated by Django 3.0.7 on 2020-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0017_auto_20200705_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_amazon_sale',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
