# Generated by Django 3.0.7 on 2020-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0018_song_song_amazon_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_youtube',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
