# Generated by Django 3.0.7 on 2020-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0019_auto_20200707_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
