# Generated by Django 3.0.7 on 2020-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0020_auto_20200715_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_single',
            field=models.CharField(choices=[('1', 'Album'), ('2', 'Single'), ('2', 'LDÖS'), ('2', 'Sonstiges')], default='1', max_length=20),
        ),
    ]
