# Generated by Django 3.0.7 on 2020-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0021_album_album_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_activ',
            field=models.BooleanField(default=True),
        ),
    ]
