# Generated by Django 3.0.7 on 2021-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0024_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_text',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True),
        ),
    ]
