# Generated by Django 3.0.7 on 2021-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0026_auto_20210321_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cover_image',
        ),
    ]
