# Generated by Django 3.0.7 on 2021-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0028_auto_20210322_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_spotify_iframe',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='song_tag',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='song',
            name='song_youtube_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='song',
            name='song_youtube_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
