# Generated by Django 3.0.7 on 2021-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0029_auto_20210328_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_spotify_iframe',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
