# Generated by Django 3.0.7 on 2021-04-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songarchiv', '0030_auto_20210328_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default='')),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='songarchiv.Album')),
                ('song', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='songarchiv.Song')),
            ],
        ),
    ]
